spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/redis
    #url: jdbc:postgresql://10.73.118.222:5432/rbpsems
    #url: jdbc:postgresql://192.168.3.200:5432/rbpsems
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: false
redis:
  clusterNodes: 10.83.7.155:9001,10.83.7.155:9002,10.83.7.155:9003,10.83.7.155:9004,10.83.7.155:9005,10.83.7.155:9006
  expireSeconds: 120
  commandTimeout: 10000 #redis操作的超时时长
led:
  base-info-url: http://172.28.3.58:8004/ServiceGetData.asmx/PISGetBaseInfo
  get-status-url: http://172.28.3.58:8004/ServiceGetData.asmx/PISGetStatus
  set-status-url: http://172.28.3.58:8004/ServiceGetData.asmx/PISSetStatus
upload:
  image: E://
httpService:
  list-url: http://10.73.118.222:5000/api/DeviceTwins/Status
  change-url: http://10.73.118.222:5000/api/DeviceTwins/WriteProperty
lightingPlan:
  interval: 5
